%Analysis_20150317_NewDCTest.m
%test the new MVPAROIDCClassify script
nCore			= 12;
strNameAnalysis	= '20150317_newdctest';

strDirOut	= DirAppend(strDirAnalysis,strNameAnalysis);
CreateDirPath(strDirOut);

ifo			= GO.SubjectInfo;
cSubject	= ifo.code.fmri;
cMask		= GO.UnionMasks;
cMask		= [cMask.core];
nMask		= numel(cMask);
cMaskCore	= [cMask; 'core'];

cMaskLabel		= upper(cMask);
cMaskLabel{5}	= 'LOC';

dimPCADC	= 10;

durRun	= GO.Param('trrun');
nRun	= size(ifo.shape,2);
kRun	= reshape(repmat(1:nRun,[durRun 1]),[],1);

cTarget	= ifo.label.te.target.shape.correct;

%chunk by operation
	cChunkTarget	= ['Blank'; ifo.condition.operation];
	[b,kChunk]		= cellfun(@(op) ismember(op,cChunkTarget),ifo.label.te.target.operation.correct,'uni',false);
	kChunk			= cellfun(@(c) c-1,kChunk,'uni',false);

%***
%cMask						= {'occ','pcu'};
%[cSubject,cTarget,kChunk]	= varfun(@(x) x(1:10),cSubject,cTarget,kChunk);

res	= MVPAROIDCClassify(...
		'output_dir'		, strDirOut		, ...
		'dir_data'			, strDirData	, ...
		'subject'			, cSubject		, ...
		'mask'				, cMask			, ...
		'dim'				, dimPCADC		, ...
		'targets'			, cTarget		, ...
		'chunks'			, kChunk		, ...
		'target_blank'		, 'Blank'		, ...
		'zscore'			, kRun			, ...
		'debug'				, 'all'			, ...
		'cores'				, nCore			, ...
		'force'				, false			  ...
		);

conf	= GO.ConfusionModels;
conf	= conf{1};
	
stat	= MVPAClassifyExtraStats(res,...
			'confusion_model'	, conf	  ...
			);

strPathOut	= PathUnsplit(strDirOut,'result','mat');
save(strPathOut,'res','stat');

%try it for operation too
	cTarget	= ifo.label.te.target.operation.correct;

	%chunk by shape
		cChunkTarget	= ['Blank'; ifo.condition.shape];
		[b,kChunk]		= cellfun(@(op) ismember(op,cChunkTarget),ifo.label.te.target.shape.correct,'uni',false);
		kChunk			= cellfun(@(c) c-1,kChunk,'uni',false);
	
	strDirOutOp	= DirAppend(strDirOut,'operation');
	res	= MVPAROIDCClassify(...
			'output_dir'		, strDirOutOp	, ...
			'dir_data'			, strDirData	, ...
			'subject'			, cSubject		, ...
			'mask'				, cMask			, ...
			'dim'				, dimPCADC		, ...
			'targets'			, cTarget		, ...
			'chunks'			, kChunk		, ...
			'target_blank'		, 'Blank'		, ...
			'zscore'			, kRun			, ...
			'debug'				, 'all'			, ...
			'cores'				, nCore			, ...
			'force'				, false			  ...
			);
	
	conf	= GO.ConfusionModels;
	conf	= conf{1};
		
	stat	= MVPAClassifyExtraStats(res,...
				'confusion_model'	, conf	  ...
				);
	
	strPathOut	= PathUnsplit(strDirOut,'result','mat');
	save(strPathOut,'res','stat');
